### ISSUE TITLE
Maven project setup

### ISSUE THREAD

**Issue by kappsegla** [fungover/storm#1]
Set up maven filestructure with pom.xml and dependencies for unit tests.

**Comment by LordRekishi** [comment]
Hade varit intressant att veta hur du gick tillväga när du är klar :) Typ Add Framework?

**Comment by DarkendHall** [comment]
Vad vill vi ha för groupId?

**Comment by kappsegla** [comment]
What about org.fungover.storm

**Comment by DarkendHall** [comment]
What main class do we want? I need to add a class to get the diretories to show in the folder structure in git.

**Comment by DarkendHall** [comment]
I will name the class Main for now.
