### ISSUE TITLE
Enable dependabot version updates

### ISSUE THREAD

**Issue by kappsegla** [fungover/storm#10]
Dependabot can fix vulnerable dependencies for you by raising pull requests with security updates.
Dependabot version updates are automated pull requests that keep your dependencies updated, even when they don’t have any vulnerabilities.

We should have that enabled for our project checking maven, docker and github-actions versions.

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates

**Comment by GreenGard** [comment]
We need to define how often we should search for new versions for each package manager. How often should we check for updates? daily, once a week or default?

**Comment by kappsegla** [comment]
Since we are going to do a release every week maybe we should use a very short time while we are working actively on the project? And change it to a longer time later.
