### ISSUE TITLE
Parsing HTTP request headers

### ISSUE THREAD

**Issue by kappsegla** [fungover/storm#11]
When communicating with a web server it's common to use HTTP as protocol. A request header consists of multiple lines of text and ends with an empty line. We need to have some functionality that can convert this header information into a more friendly format. From a string or a list of strings to some sort of Header object that can be queried for information.
The first line has request type followed by the file and folder we are looking for and ends with the version of the HTTP protocol.
The following lines consists of a key, value pair separated with

Ex:
GET /home.html HTTP/1.1
Host: developer.mozilla.org
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Connection: keep-alive

https://developer.mozilla.org/en-US/docs/Glossary/Request_header

**Comment by FelixJacobsen** [comment]
I'm suggesting we look into the "HttpServletRequest" interface containing alot of useful methods. "getMethod" & "getHeader" as example. Would be nice to also have a method containing a list or string-array and returning a object reference which handles saving. This way the method will be valid for our JUnit5 testing.

**Comment by kappsegla** [comment]
> we look into the "HttpServletRequest" interface containing alot of useful methods. "getMethod" & "getHeader" as example. Would be nice to also have a method containing a list or string-array and returning a object reference which handles saving. This way the method will be valid for our JUnit5 testing.

Sounds like a good inspiration what type of methods that could be built into our own code.
