### ISSUE TITLE
MIME types

### ISSUE THREAD

**Issue by kappsegla** [fungover/storm#12]
When sending a response from a webserver one of the response header values is the MIME type for the file/content we are transfering. For example if someone is requesting a file called cat.png we need to set the key Content-type to image/png.

We should have a method that from inspecting a filename and its ending can return the right MIME type for some common image formats, textfiles as html, css and application files as zip and pdf.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types

Input to the method can probably be a filename as a String or maybe a Path object? Overloaded versions?
Where to place methods and in what packet?

**Comment by GreenGard** [comment]
I think it would be most beneficial to use a Path object, having the method save specific data from the input.

Further development could include overloaded version of this method to handle the same functionality with a string input instead.

A good location for this method would be in src/main/java/org/fungover/storm/FileHandler

**Comment by HelenaHalldinITHS** [comment]
Not sure if GreenGard is working on this or accedently assigned/unassigned? I will give it a go since it is needed for further development.
