### ISSUE TITLE
Adding support for logging framework

### ISSUE THREAD

**Issue by kappsegla** [fungover/storm#13]
We need support for logging and I suggest that we add dependencies for a logging framework and configure the logging to write to standard output for the time being. What about using Log4j2? https://stackify.com/compare-java-logging-frameworks/
To showcase how the logging works we can add a first logmessage when the server starts.

**Comment by ChristianLofqvist** [comment]
Had to change thread sleep in ServerTest.java from 500 ms to 1000 ms because the server object didn't have enough time to initialize.
