### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by kappsegla** [fungover/storm#15]
Create a dockerfile that can build an image for running the application. Alpine based jre for java17 looks to be available here now:
https://hub.docker.com/layers/eclipse-temurin/library/eclipse-temurin/17-jre-alpine/images/sha256-839f3208bfc22f17bf57391d5c91d51c627d032d6900a0475228b94e48a8f9b3?context=explore

**Comment by GreenGard** [comment]
Would be good if  the dockerfile could be placed in the following directory: .github/workflows/ for dependabot support.

**Comment by kappsegla** [comment]
> Would be good if the dockerfile could be placed in the following directory: .github/workflows/ for dependabot support.

Why would that be needed for dependabot? dependabot.yml should be in .github folder and then we tell it where to find dockerfile like this.
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      
      Dockerfile should be in the root folder of the project for easy build and folder/file reference.

**Comment by kappsegla** [comment]
Another nice thing to have would be a folder that can be mounted from outside the container with files for our server. Like a webroot folder. To achieve that we can use the command VOLUME https://docs.docker.com/engine/reference/builder/#volume
