### ISSUE TITLE
Open server socket

### ISSUE THREAD

**Issue by kappsegla** [fungover/storm#3]
When the program starts it should open a serversocket and listen for incomming connections.
Each incomming connection should be handled in it's own thread.

**Comment by LordRekishi** [comment]
Should I use an out/input stream to confirm connection to the server? Or how could I test that a connection is established and put into a new thread?

**Comment by kappsegla** [comment]
When accepting an incoming connection from the ServerSocket it will return a Socket object. From this object we can retrieve things like input and output streams and connected ip and other things. So we can transfer a reference for that object into the treads method.
For verification of this functionality you can open the output stream and send some simple Hello World text.
When it comes to writing tests for this we can't really do a unit test without making the code more testable. So if you want to verify that the code starts a server and calls accept waiting for connections it can be done using an interface and dependency injection:
https://stackoverflow.com/questions/38957460/how-to-test-method-that-internally-creates-and-uses-a-serversocket

Later in the project we can verify this behaviour by starting the whole server and using HttpClient for making calls against the server as a form of Integration tests.

**Comment by kappsegla** [comment]
https://docs.oracle.com/javase/tutorial/networking/sockets/clientServer.html

**Comment by LordRekishi** [comment]
Issue resolved
