### ISSUE TITLE
Adding code inspection

### ISSUE THREAD

**Issue by kappsegla** [fungover/storm#33]
To help in the code review we can add some automatic code scanning to our pipeline.

Github has a built in CodeQL analysis engine that can be used: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning

Or we can use the same code scanning that we have in IntelliJ.
https://www.jetbrains.com/help/qodana/qodana-github-action.html

I suggest that we add code scanning with qodana and also enable Pull request quality gate.

An alternative that isn't free could be https://www.sonarqube.org/github-integration/ where it's possible to request a free 14-day trial.

We could also run our own free version of sonarqube as a docker container on some computer that is connected to internet.
https://github.com/SonarSource/sonarqube-quality-gate-action

**Comment by DarkendHall** [comment]
Can't you get Github actions to run a docker image as described here:  https://stackoverflow.com/questions/57549439/how-do-i-use-docker-with-github-actions#:~:text=2%20Answers&text=GitHub%20actions%20provision%20a%20virtual,a%20workflow%20inside%20a%20container. That way we could use Sonarqube without having to pay, or need someone to keep their pc running 24/7.

**Comment by kappsegla** [comment]
> Can't you get Github actions to run a docker image as described here: https://stackoverflow.com/questions/57549439/how-do-i-use-docker-with-github-actions#:~:text=2%20Answers&text=GitHub%20actions%20provision%20a%20virtual,a%20workflow%20inside%20a%20container. That way we could use Sonarqube without having to pay, or need someone to keep their pc running 24/7.

Yes I think that's possible. And then you have to mount the folders used for saving settings in sonarqube to some github cache so it doesn't have to start from scratch each time. But I can host a docker image of sonarqube on a public ip running 24/7.
