### ISSUE TITLE
Default website files

### ISSUE THREAD

**Issue by kappsegla** [fungover/storm#37]
When starting the server in a docker container we want a folder named /webroot to contain all our files that the server should be able to server. To change them we can use the command `docker run -v /host/path:/webroot` to mount a folder from the host containing our website.

But when starting the container without a mount it would be good to have some default file like an index.html file added in the /webroot folder of the docker image.

Create a folder containing an index.html file with some valid Html5 code in it. If using an image as logotype for our server put the image in the same folder. Try to keep the filesizes small.
Update Dockerfile to copy this folder into the /webroot folder of the docker image.

**Comment by kappsegla** [comment]
Can we use git large file storage to store the files?
https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage

**Comment by LordRekishi** [comment]
I removed the mkdir webroot line from Dockerfile and replaced it with the following

`COPY --from=build /src/webroot /webroot`

This worked when I started and ran the container locally.

**Comment by Vimbayinashe** [comment]
> I removed the mkdir webroot line from Dockerfile and replaced it with the following
> 
> `COPY --from=build /src/webroot /webroot`
> 
> This worked when I started and ran the container locally.

Thank-you! 🙂
