### ISSUE TITLE
Logging with log4j

### ISSUE THREAD

**Issue by DarkendHall** [fungover/storm#40]
We added support for logging with log4j but we are still using printStackTrace() in several places in our code. Maybe we should change this to log the error message with log4j?

**Comment by ErikssonF** [comment]
Do we want to add custom messages for each errors such as "LOGGER.error("Invalid port! " + e.getMessage());" or are we satisfied with just "e.getMessage()"?

**Comment by ErikssonF** [comment]
Opted to leave out custom messages in pull request as SonarLint marked them as major issues.
