### ISSUE TITLE
Handle mime types with multiple file endings

### ISSUE THREAD

**Issue by kappsegla** [fungover/storm#69]
For some MIME types multiple file endings will result in the same content-type.
Example:
Both .jpeg and .jpg is a JPEG images and should result in a MIME type of image/jpeg
Another example is .htm .html and .tif .tiff

**Comment by kappsegla** [comment]
When working with this bug start your bugfix branch from tag v1.0.0 and not the latest main commit.

**Comment by HelenaHalldinITHS** [comment]
Should I only fix the code so it can handle the problem (and add one of the above, ex jpeg and jpg) or should I add all of the above (and more)?

**Comment by HelenaHalldinITHS** [comment]
> If creating a new branch based of latest version of main we can apply this fix also to the v1.0.0 release by creating a branch starting from this tag and maybe name it release/1.0. Then we can cherrypick this fix into the branch and make a release for v1.0.1
> 
> An alternative is to checkout v1.0.0 as a new branch, hotfix-69 and fix the problem before making a new release. Don't forget to also merge this function into main so the bug isn't kept there.
> 
> We could have handled this in other ways if we had created development or a release branch from start.

I chose option two. I fixed it and made a pull request. When it has been reviewed and approved, should I leave the branch (not delete it) so we can make a release from it? 

Also, can I make a release or are you the only one who can do it?

**Comment by kappsegla** [comment]
Lets look into this tomorrow when we meet at 9.

**Comment by HelenaHalldinITHS** [comment]
solved in pull request #73
