### ISSUE TITLE
Adding workflow badge to README.md

### ISSUE THREAD

**Issue by kappsegla** [fungover/storm#7]
It's possible to add a badge in the README.md file showing build status for the project. Would be a nice feature to have on the project showing the current status for the automatic build process.
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge

**Comment by Vimbayinashe** [comment]
I am un-assigning myself from this issue.

**Comment by mrtorks** [comment]
@kappsegla Can I take this on?

**Comment by LordRekishi** [comment]
> @kappsegla Can I take this on?

Don't think you need to ask really. Just assign yourself :)

**Comment by FelixJacobsen** [comment]
![storm](https://user-images.githubusercontent.com/89127725/151663600-310e9777-53db-417b-82b4-cf92e189a54f.png)

In addition to workflow status, it's possible to get badges for issues/pull-requests. Is this something we want?

I also found a badge for a release date if we want to provide one.

**Comment by LordRekishi** [comment]
> 

All those look useful. My vote is to add them all.

**Comment by Vimbayinashe** [comment]
That looks great Felix!
