### ISSUE TITLE
Wrong module name

### ISSUE THREAD

**Issue by kappsegla** [fungover/storm#9]
It's strongly recommended that all modules be named according to the reverse Internet domain-name convention.
A module's name should correspond to the name of its principal exported API package, which should also follow that convention.
Therefor our module should be named org.fungover.storm

**Comment by DarkendHall** [comment]
It seems I forgot to rename the module when I created the file, oversight on my part...

**Comment by LordRekishi** [comment]
I guess Issue#3 need to be merged first before you can do this issue since I add another module-info file in that merge

**Comment by OscarStjernfeldt** [comment]
Fixed in #27
