### ISSUE TITLE
I'm a teapot

### ISSUE THREAD

**Issue by kappsegla** [fungover/storm#95]
The HTTP 418 I'm a teapot client error response code indicates that the server refuses to brew coffee because it is, permanently, a teapot. A combined coffee/tea pot that is temporarily out of coffee should instead return 503. This error is a reference to Hyper Text Coffee Pot Control Protocol defined in April Fools' jokes in 1998 and 2014.

Let us implement an endpoint in our server called /coffee and if we tries to access that we should get the error message 418 I'm a teapot.

**Comment by LummIIi** [comment]
I will take this one on.
